// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiFqh1NSqHzGTbKXNlSCk74JHaZWJILU4',
    appId: '1:523300852152:web:da47e72db5caa9406dff4d',
    messagingSenderId: '523300852152',
    projectId: 'carpoolin3',
    authDomain: 'carpoolin3.firebaseapp.com',
    storageBucket: 'carpoolin3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgg_DBOFKkAHzV6BkOWpEYhwL27jtVbtY',
    appId: '1:523300852152:android:f08de28dce65f4e56dff4d',
    messagingSenderId: '523300852152',
    projectId: 'carpoolin3',
    storageBucket: 'carpoolin3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCJSwoyRj1AcIEPfWBb3kD8WgsKTr9JNU',
    appId: '1:523300852152:ios:bf4d9c40ba7cee116dff4d',
    messagingSenderId: '523300852152',
    projectId: 'carpoolin3',
    storageBucket: 'carpoolin3.appspot.com',
    iosBundleId: 'com.example.carpooling3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCJSwoyRj1AcIEPfWBb3kD8WgsKTr9JNU',
    appId: '1:523300852152:ios:bf4d9c40ba7cee116dff4d',
    messagingSenderId: '523300852152',
    projectId: 'carpoolin3',
    storageBucket: 'carpoolin3.appspot.com',
    iosBundleId: 'com.example.carpooling3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiFqh1NSqHzGTbKXNlSCk74JHaZWJILU4',
    appId: '1:523300852152:web:e02f95be5eb6805e6dff4d',
    messagingSenderId: '523300852152',
    projectId: 'carpoolin3',
    authDomain: 'carpoolin3.firebaseapp.com',
    storageBucket: 'carpoolin3.appspot.com',
  );
}
